import Foundation

/// Yomitan's de-inflection, ported.
///
/// Its rules are typed: each declares which grammatical conditions it consumes and
/// which it produces, so a chain can only run through forms that could actually have
/// produced the word. A hand-written table without that check over-generates — ours
/// turned やって into 夜雨 "night rain" and いれば into 入れ歯 "false tooth", and
/// needed extra filters to suppress what it invented.
///
/// Rules come from `japanese-transforms.json`, generated by `scripts/build-transforms.mjs`
/// from the vendored Yomitan source. See `vendor/yomitan/` — GPL-3.0.
final class LanguageTransformer {
    struct TransformedText {
        let text: String
        let conditions: Int
    }

    private struct Rule {
        let isWholeWord: Bool
        let inflected: String
        let deinflected: String
        let conditionsIn: Int
        let conditionsOut: Int
    }

    private struct Transform {
        let id: String
        let rules: [Rule]
    }

    private let transforms: [Transform]

    static let japanese: LanguageTransformer? = {
        guard let url = Bundle.main.url(forResource: "japanese-transforms", withExtension: "json"),
              let data = try? Data(contentsOf: url) else { return nil }
        return LanguageTransformer(data: data)
    }()

    init?(data: Data) {
        guard let descriptor = try? JSONDecoder().decode(Descriptor.self, from: data) else { return nil }
        let flags = Self.conditionFlags(descriptor.conditions)

        transforms = descriptor.transforms.map { transform in
            Transform(id: transform.id, rules: transform.rules.map { rule in
                Rule(isWholeWord: rule.type == "wholeWord",
                     inflected: rule.inflected,
                     deinflected: rule.deinflected,
                     conditionsIn: Self.flags(for: rule.conditionsIn, in: flags),
                     conditionsOut: Self.flags(for: rule.conditionsOut, in: flags))
            })
        }
    }

    /// Every form `text` could be an inflection of, the word itself first.
    ///
    /// Breadth-first, exactly as upstream: each result is itself a candidate for
    /// further de-inflection, so 食べさせられたかった unwinds one step at a time.
    func transform(_ text: String) -> [TransformedText] {
        var results = [TransformedText(text: text, conditions: 0)]
        // A trace per result, so a rule cannot be applied to the same text twice.
        var traces: [[String]] = [[]]

        var index = 0
        while index < results.count {
            let current = results[index]
            let trace = traces[index]
            index += 1

            for transform in transforms {
                for (ruleIndex, rule) in transform.rules.enumerated() {
                    guard Self.conditionsMatch(current.conditions, rule.conditionsIn) else { continue }
                    guard rule.isWholeWord
                            ? current.text == rule.inflected
                            : current.text.hasSuffix(rule.inflected) && current.text.count > rule.inflected.count
                    else { continue }

                    let frame = "\(transform.id)|\(ruleIndex)|\(current.text)"
                    guard !trace.contains(frame) else { continue }

                    let stem = rule.isWholeWord
                        ? ""
                        : String(current.text.dropLast(rule.inflected.count))
                    results.append(TransformedText(text: stem + rule.deinflected,
                                                   conditions: rule.conditionsOut))
                    traces.append(trace + [frame])
                }
            }
        }
        return results
    }

    /// No conditions yet means anything may apply; otherwise the sets must overlap.
    private static func conditionsMatch(_ current: Int, _ next: Int) -> Bool {
        current == 0 || (current & next) != 0
    }

    // MARK: - Condition flags

    /// A leaf condition gets its own bit; a parent is the union of its children, so
    /// testing against "any verb" matches every verb class.
    private static func conditionFlags(_ conditions: [String: Descriptor.Condition]) -> [String: Int] {
        var flags: [String: Int] = [:]
        var nextBit = 0
        var pending = Set(conditions.keys)

        while !pending.isEmpty {
            var settled: [String] = []
            for name in pending {
                guard let condition = conditions[name] else { settled.append(name); continue }
                guard let children = condition.subConditions, !children.isEmpty else {
                    flags[name] = 1 << nextBit
                    nextBit += 1
                    settled.append(name)
                    continue
                }
                let resolved = children.compactMap { flags[$0] }
                guard resolved.count == children.count else { continue }   // children first
                flags[name] = resolved.reduce(0, |)
                settled.append(name)
            }
            if settled.isEmpty { break }                                   // malformed; stop
            settled.forEach { pending.remove($0) }
        }
        return flags
    }

    private static func flags(for names: [String], in map: [String: Int]) -> Int {
        names.compactMap { map[$0] }.reduce(0, |)
    }

    // MARK: - On-disk shape

    private struct Descriptor: Decodable {
        let conditions: [String: Condition]
        let transforms: [Transform]

        struct Condition: Decodable {
            let isDictionaryForm: Bool
            let subConditions: [String]?
        }
        struct Transform: Decodable {
            let id: String
            let rules: [Rule]
        }
        struct Rule: Decodable {
            let type: String
            let inflected: String
            let deinflected: String
            let conditionsIn: [String]
            let conditionsOut: [String]
        }
    }
}
